// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnueWXW-25hYH1mThF5S2ViLVCdpOYGt0',
    appId: '1:1052267226994:web:3af379ebf6ed2138395feb',
    messagingSenderId: '1052267226994',
    projectId: 'todo-app-8291d',
    authDomain: 'todo-app-8291d.firebaseapp.com',
    storageBucket: 'todo-app-8291d.appspot.com',
    measurementId: 'G-1KZY998BMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDN1qFMkA9jtrYIx07MXMY0QrYhxp39hQ',
    appId: '1:1052267226994:android:e99c3f1ba10ed899395feb',
    messagingSenderId: '1052267226994',
    projectId: 'todo-app-8291d',
    storageBucket: 'todo-app-8291d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrs1zv4jsr7i-anAD6akZc80UXKA4HcaM',
    appId: '1:1052267226994:ios:c63c66b1eec325ad395feb',
    messagingSenderId: '1052267226994',
    projectId: 'todo-app-8291d',
    storageBucket: 'todo-app-8291d.appspot.com',
    iosBundleId: 'com.example.todoAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrs1zv4jsr7i-anAD6akZc80UXKA4HcaM',
    appId: '1:1052267226994:ios:c63c66b1eec325ad395feb',
    messagingSenderId: '1052267226994',
    projectId: 'todo-app-8291d',
    storageBucket: 'todo-app-8291d.appspot.com',
    iosBundleId: 'com.example.todoAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnueWXW-25hYH1mThF5S2ViLVCdpOYGt0',
    appId: '1:1052267226994:web:4321ecddb35b18c5395feb',
    messagingSenderId: '1052267226994',
    projectId: 'todo-app-8291d',
    authDomain: 'todo-app-8291d.firebaseapp.com',
    storageBucket: 'todo-app-8291d.appspot.com',
    measurementId: 'G-4DP02N9ZX1',
  );
}
